# Site settings
title: East Midlands Freelancers
email: hello@eastmidlandsfreelancers.com
baseurl: ""
url: "http://eastmidlandsfreelancers.com"
twitter_username: katherinecory
github_username: katherinecory
safe: true
