title: East Midlands Freelancers
tagline: "A directory of digital freelancers in Derbyshire, Nottinghamshire, Lincolnshire, Leicestershire and the East Midlands"
author:
  email: hello@eastmidlandsfreelancers.com
  twitter: katherinecory
  github: katherinecory
baseurl: ""
url: "http://eastmidlandsfreelancers.com"
safe: true
